ARG GO_BUILDER_IMAGE=m.daocloud.io/docker.io/library/golang:1.21-alpine
ARG RUNTIME_IMAGE=m.daocloud.io/docker.io/library/alpine:3.20

FROM ${GO_BUILDER_IMAGE} AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/lab4-gateway ./cmd/cloud-gateway

FROM ${RUNTIME_IMAGE}
WORKDIR /app
COPY --from=builder /out/lab4-gateway /app/lab4-gateway
EXPOSE 9310 9311
ENTRYPOINT ["/app/lab4-gateway"]
